name: .NET

on:
    push:
        branches: ["master"]
    pull_request:
        branches: ["master"]

jobs:
    build:
        runs-on: windows-latest

        steps:
            - uses: actions/checkout@v4
            - name: Setup .NET
              uses: actions/setup-dotnet@v3
              with:
                  dotnet-version: 6.0
            - name: Restore dependencies
              run: dotnet restore
            - name: Build
              run: dotnet build --no-restore
            # - name: Run ServerClient integration tests
            #   run: dotnet test --filter TestServerClient --no-build
            - name: Run other tests
              run: dotnet test --filter FullyQualifiedName!=TinyCiv.Server.Client.IntegrationTests.TestServerClient --no-build
